<a href="https://colab.research.google.com/github/yazhinil/FMML20230017/blob/main/LAB%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Question 0

#string

city= "loNdON"
print(city.upper())
print(city.lower())
print(city.title())

#list
list= ['a', 'b', 'c','d']
list.extend(['e', 'f'])
print (list)

list.reverse()
print (list)

list.pop()

#tuple
tuple= (1,2,3,4,5)
a= tuple.index(4)
print(a)
length= len(tuple)
print(length)
max(tuple)

#set

set1 = set(["a", "b", "c"])
set1.add("d")
print(set1)

set1.remove("b")
print(set1)

set1.pop()

#dictionary

dict= {1: 'a', 2:'b', 3:'c', 4:'d'}
print(dict.keys())

print(dict.get(2))

dict.clear()
print(dict)



LONDON
london
London
['a', 'b', 'c', 'd', 'e', 'f']
['f', 'e', 'd', 'c', 'b', 'a']
3
5
{'b', 'a', 'd', 'c'}
{'a', 'd', 'c'}
dict_keys([1, 2, 3, 4])
b
{}


In [1]:
#Question 1

def reverse(s):
    str = ""
    for i in s:
        str = i + str
    return str


def one(a:str , b:str):
  b=(str)(reverse(a)+b)

  print(b)

one("ball", "bat")


llabbat


In [3]:
#Question 2


work_hours = [('Abby',100, 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]

hour=[]
for name,hours,gender in sorted(work_hours):
  hour.append(hours)

m= max(hour)
ind= hour.index(m)
most_hours= work_hours[ind]

def person(name, amount):
  print(f"The female worker that worked the most hours is {name} and she should be paid {amount}")

person(most_hours[0], most_hours[1]*20)



The female worker that worked the most hours is Penny and she should be paid 18400


In [4]:
#Question 3
import numpy as np

#a
arr= np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
print(np.vstack(arr))

#b
arr1= arr* [1,2,3,4,5]
print(arr1)



[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
